### ISSUE TITLE
Badges broken since repository was moved

### ISSUE THREAD

**Issue by bittner** [PythonTurtle/PythonTurtle#137]
The badges on top of the README are broken [since we moved the project](https://github.com/PythonTurtle/PythonTurtle/pull/136#issuecomment-525205335) into its own GitHub organization. That should be easy to fix, it's just URL values.

**Comment by bittner** [comment]
I see that we now need to rename the projects on Travis CI and AppVeyor, too.

In the AppVeyor project I could rename the reference to the GitLab repository project, but the URL seems to be bound to the user name (it won't take an organization name), hence it will stay as it is.

@cool-RR Can you see in the [Travis project settings](https://travis-ci.org/cool-RR/PythonTurtle/settings) whether there is a way to rename or move the project? We would otherwise lose the build history. In Travis CI the relationship between GitHub project name and Travis CI project names is more strict, for what I understand (so, it could be we need to initialize a new CI project).

**Comment by cool-RR** [comment]
I'm not seeing a way to move the project on the Travis settings page. I don't think that losing the build history is a big deal.

**Comment by bittner** [comment]
It looks like the badges are intact now, but the AppVeyor integration is broken. I'll try to add the [now missing webhook](https://github.com/PythonTurtle/PythonTurtle/settings/hooks).

**Comment by bittner** [comment]
Not sure, but our [GitHub organization settings](https://github.com/organizations/PythonTurtle/settings/oauth_application_policy) _do_ have some AppVeyor integration in place.

In any case, I now have added the webhook [from the AppVeyor settings](https://ci.appveyor.com/project/cool-RR/pythonturtle/settings).
