### ISSUE TITLE
left and right API's does not work for non-integers

### ISSUE THREAD

**Issue by umangparekh** [PythonTurtle/PythonTurtle#139]
t.left(30/9) does not produce accurate results and divides the 30 degrees into 10 parts as opposed to the expected 9 parts.

**Comment by bittner** [comment]
Thanks for spamming us. You are awesome.

**Comment by bittner** [comment]
If this was meant as a screenshot upload it to GitHub directly. Otherwise it will be deleted (as untrusted) again.

**Comment by cool-RR** [comment]
@umangparekh You need to use `30/9.0` because it's Python 2.

**Comment by umangparekh** [comment]
@cool-RR Thanks! (feeling silly)
