### ISSUE TITLE
"setworldcoordinates" cause the failure of "hideturtle"

### ISSUE THREAD

**Issue by jlTY-2008** [PythonTurtle/PythonTurtle#166]
Writing the following code,I gets a wrong result which means Pen shows with "hideturtle" and "isvisible" returns "True"
```
import turtle as t

pen = t.Pen()
pen.hideturtle()

screen = t.Screen()
screen.setworldcoordinates(-100, -100, 100, 100)

print(pen.isvisible())

t.done()
```
In Windows 11 and Python 3.11.4

**Comment by bittner** [comment]
You're mixing the functionality of PythonTurtle and the Python standard library's [turtle](https://docs.python.org/3/library/turtle.html) module.

Please follow the help screen's usage instructions (<kbd>F1</kbd>) or execute `dir()` to see the available commands.

Does that help?

**Comment by jlTY-2008** [comment]
> You're mixing the functionality of PythonTurtle and the Python standard library's [turtle](https://docs.python.org/3/library/turtle.html) module.
> 
> Please follow the help screen's usage instructions () or execute to see the available commands.F1`dir()`
> 
> Does that help?

Sorry.I'll submit the bug report on [cpython](https://github.com/python/cpython)
